### ISSUE TITLE
Not able to see virtual environment for python 

### ISSUE THREAD

**Issue by Divyadarshee** [ChristianLempa/dotfiles#17]
Not able to see virtual environment for python getting activated with the current config of starship. I confess that i shamelessly copied your config for starship either because i was lazy and/or because i do not trust my customization skills, But there is no doubt i loved your terminal's look so i went ahead with it. Now obviously, since i have not explored starship documentation i was hoping if someone has already gone through this and fixed it.
After activating the venv for python there is no difference in the console.

Please help me if anyone knows what needs to be done.

[Edit]
Forgot to show screenshots of the current issue -

<img width="557" alt="image" src="https://github.com/ChristianLempa/dotfiles/assets/28804797/31a17269-7a32-4fd0-8d01-4d2559ea4edb">

I tried adding the bellow configuration but that too didnt help
`[python]`
`format = '[($virtualenv )]($style)'`

**Comment by Divyadarshee** [comment]
> I've disabled it in my config because I felt it spamming my terminal too much, feel free to enable it in your config, using the
> 
> ```toml
> [python]
> disabled = true  # -> switch to false
> ```
> 
> You find more helpful documents on the starship config page: https://starship.rs/config/#python

Really sorry i should have checked and figured out this small change.
Thanks @ChristianLempa

**Comment by ChristianLempa** [comment]
No worries, don't hesitate to reach out if you need help :)
