### ISSUE TITLE
Major contrast issue in helix color scheme and terminal color scheme

### ISSUE THREAD

**Issue by hariienesh** [ChristianLempa/dotfiles#19]
![image](https://github.com/ChristianLempa/dotfiles/assets/76608849/e923d028-7a0e-4268-905f-0b12e62a140b)

**Comment by ChristianLempa** [comment]
@hariienesh that's a problem in all warp themes, so I don't think this is related to the color theme, but either to the terminal emulator, or the helix program itself.
